version: '3'

networks:
  common:
    external: true

services:
  wx_send_many_endpoint:
    build:
      context: ./con
    volumes:
      - ../:/app/code
    expose:
      - "8080"
    networks:
      - default
      - common
    working_dir: /app/code
    command: /bin/sh ./run.sh
